### ISSUE TITLE
misc

### ISSUE THREAD

**Issue by vegarringdal** [midrissi/wakanda-node#1]
it should say...

```
   var wakanda = require('wakanda-node');
```

on changing I had to add "attibutes"

```
   if(emp){
        emp.attributes.firstname = 'Martin';
        emp.save();
    }
```

You are not much fan of comments in your coding :-)

**Comment by midrissi** [comment]
Hello Vegar,

Thank you for reporting the issue, I will fixe it!

To change an attribute, I have developed locally the "wakanda style", but I have forgotten to push it :(
The best way for the moment is to use the "set" (http://backbonejs.org/#Model-set) method.

``` js
if(emp){
        emp.set('firstname', 'Martin');
        emp.save();
}
```

For the comments, I am working on the repo just on my free time, I am planning to add some documentation later.

Thanks again :+1:
